version: 2.1

orbs:
  teak: teak/sdk-utils@dev:alpha

jobs:
  setup:
    docker:
      - image: cimg/base:2021.04

    steps:
      - teak/terraform-install:
          version: 1.0.5
      - teak/packer-install:
          version: 1.7.4

  build-production:
    docker:
      - image: cimg/base:2021.04

    steps:
      - checkout
      - teak/terraform-install:
          version: 1.0.5
      - teak/terraform-init:
          path: "terraform"
      - teak/terraform-plan:
          workspace: "production"
          path: "terraform"


  deploy-production:
    docker:
      - image: cimg/base:2021.04

    steps:
      - checkout
      - teak/terraform-install:
          version: 1.0.5
      - teak/terraform-init:
          path: "terraform"
      - teak/terraform-apply:
          workspace: "production"
          path: "terraform"


workflows:
  version: 2
  build:
    jobs:
      - setup
      - teak/terraform-plan:
          path: "terraform"
          workspace: "development"
          context: AWS-Write
          requires:
            - setup
          filters:
            branches:
              only:
                - develop
      - hold-develop:
          type: approval
          requires:
            - teak/terraform-plan
          filters:
            branches:
              only:
                - develop
      - teak/terraform-apply:
          path: "terraform"
          workspace: "development"
          context: AWS-Write
          requires:
            - hold-develop
          filters:
            branches:
              only:
                - develop
      - teak/packer-build:
          pre-steps:
            - run:
                command: sudo apt-get update && sudo apt-get install -y ansible
          path: "packer"
          var: "region=us-east-1,environment=development"
          artifact_path: packer/build
          context: AWS-Write
          requires:
            - teak/terraform-apply
          filters:
            branches:
              only:
                - develop
