version: 2.1

orbs:
  teak: teak/sdk-utils@0.1

jobs:
  setup:
    docker:
      - image: cimg/base:2021.04

    steps:
      - teak/terraform-install:
          version: 1.0.5
      - teak/packer-install:
          version: 1.7.5

workflows:
  version: 2
  build-development:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - develop
      - teak/terraform-plan:
          name: "Plan (Development)"
          path: "terraform"
          workspace: "development"
          context: AWS-Write
          requires:
            - setup
      - hold:
          name: "Human, your approval is required (Development)"
          type: approval
          requires:
            - "Plan (Development)"
      - teak/terraform-apply:
          name: "Apply (Development)"
          path: "terraform"
          workspace: "development"
          context: AWS-Write
          requires:
            - "Human, your approval is required (Development)"
      - teak/packer-build:
          version: 1.7.5
          name: "Generate Images (Development)"
          pre-steps:
            - run:
                command: sudo apt-get update && sudo apt-get install -y ansible awscli
          path: "packer"
          var: "region=us-east-1,environment=development"
          context:
            - AWS-Write
            - Vagrant
          requires:
            - "Apply (Development)"
  build-production:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - main
      - teak/terraform-plan:
          name: "Plan (Production)"
          path: "terraform"
          workspace: "production"
          context: AWS-Write
          requires:
            - setup
      - hold:
          name: "Human, your approval is required (Production)"
          type: approval
          requires:
            - "Plan (Production)"
      - teak/terraform-apply:
          name: "Apply (Production)"
          path: "terraform"
          workspace: "production"
          context: AWS-Write
          requires:
            - "Human, your approval is required (Production)"
      - teak/packer-build:
          version: 1.7.5
          name: "Generate Images (Production)"
          pre-steps:
            - run:
                command: sudo apt-get update && sudo apt-get install -y ansible awscli
          path: "packer"
          var: "region=us-east-1,environment=production"
          except: "amazon-ebs.debian_arm64"
          context:
            - AWS-Write
            - Vagrant
          requires:
            - "Apply (Production)"
